site_name: Curso Apphive Cero a Experto (DevITM)
site_url: https://example.com/
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
    - search.highlight
    - search.suggest
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
nav:
  - Inicio: index.md
  - Lección 1: 
      - Guía: lessons/cap_01_proyecto.md
      - Flujos de trabajo: lessons/flows_mermaid_cap01.md
      - Checklist: lessons/checklist_cap01.csv
      - Dataset: lessons/dataset_cap01.json
  - Apéndices:
      - Glosario: appendix_glossary.md