site_name: Apphive Mega Tutorial
site_url: https://cygnixit.github.io/tutorial-apphive
repo_url: https://github.com/Cygnixit/tutorial-apphive
repo_name: Cygnixit/tutorial-apphive
edit_uri: edit/main/docs/
theme:
  name: material
  language: es
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.top
plugins:
  - search
  - with-pdf:
      output_path: Apphive_Mega_Tutorial.pdf
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - tables
nav:
  - Inicio: 00-introduccion.md
  - Glosario: 05-glosario.md
  - Fundamentos:
      - Fundamentos: 10-fundamentos.md
      - Data Manager: 12-data-manager.md
      - Navegación: 14-navegacion.md
  - UI:
      - Buttons: 20-ui-buttons.md
      - Inputs: 20-ui-inputs.md
      - Lists: 20-ui-lists.md
      - Cards: 20-ui-cards.md
      - Modals: 20-ui-modals.md
      - Forms: 20-ui-forms.md
      - Tabs: 20-ui-tabs.md
      - Tables: 20-ui-tables.md
      - Charts: 20-ui-charts.md
      - Images: 20-ui-images.md
      - Maps: 20-ui-maps.md
  - Backend y APIs:
      - APIs REST: 30-apis-rest.md
      - Autenticación: 31-auth.md
      - Geo & Mapas: 32-geo-mapas.md
      - Storage: 33-storage.md
  - Pagos:
      - Intro: 42-pagos-intro.md
      - Stripe avanzado: 43-stripe-avanzado.md
      - Mercado Pago marketplace: 44-mercado-pago-marketplace.md
      - Buenas prácticas: 45-pagos-buenas-practicas.md
  - Operación:
      - Build & Deploy: 50-build-deploy.md
      - Estado global: 60-estado-global.md
      - Offline & Retry: 62-offline-retry.md
      - Roles y permisos: 64-roles-permisos.md
      - Logging & auditoría: 66-logging-auditoria.md
      - Modelado de datos: 67-modelado-datos.md
      - Performance: 70-performance.md
      - Analítica: 72-analitica-eventos.md
      - i18n: 74-i18n.md
      - Testing & QA: 76-test-qa.md
      - Seguridad: 78-seguridad.md
      - Versionado: 80-versionado.md
      - SLO & Alertas: 82-slo-alertas.md
      - Costos: 84-costos.md
      - Facade: 86-facade.md
      - Runbooks: 88-runbooks.md
  - Índice maestro: 90-indice-maestro.md