
site_name: Apphive Mega Tutorial
site_url: https://cygnixit.github.io/tutorial-apphive
repo_url: https://github.com/Cygnixit/tutorial-apphive
repo_name: Cygnixit/tutorial-apphive
edit_uri: edit/main/docs/
theme:
  name: material
  language: es
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.top
plugins:
  - search
  - with-pdf:
      output_path: Apphive_Mega_Tutorial.pdf
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - tables
nav:
  - Inicio: 00-introduccion.md
  - Glosario: 05-glosario.md
  - Ruta guiada (v3):
      - Panorama: v3-00-ruta-guiada.md
      - CRUD Clientes: v3-01-crud-clientes.md
      - Auth & Sesiones: v3-02-auth-sesiones.md
      - Pagos E2E: v3-03-pagos-flujo-completo.md
      - Mapas y rutas: v3-04-mapas-rutas.md
      - Push: v3-05-notificaciones-push.md
      - Testing & QA: v3-06-testing-qa-extenso.md
      - Deploy & CI: v3-07-deploy-ci.md
      - Troubleshooting: v3-08-troubleshooting.md
      - Ejercicios: v3-09-ejercicios.md
      - Glosario ext.: v3-10-anexos-glosario-ext.md
